/** Copyright (C) Enzo 2025-2026 */
/** Copyright (C) Enzo inc. 2025-2026 */
/** Copyright (C) Enzo LLC 2025-2026 */
val tabelaLetras = mutableListOf<String>()
val letras = mutableListOf<String>()
val palavras = mutableListOf<String>()
val palavrasMasculinas = mutableListOf<String>()
val palavrasFemininas = mutableListOf<String>()
val comidas = mutableListOf<String>()
val saudações = mutableListOf<String>()
val verbos = mutableListOf<String>()
val bebidas = mutableListOf<String>()
val gírias = mutableListOf<String>()
/** LETRAS */
tabelaLetras.add("q")
tabelaLetras.add("w")
tabelaLetras.add("e")
tabelaLetras.add("r")
tabelaLetras.add("t")
tabelaLetras.add("y")
tabelaLetras.add("u")
tabelaLetras.add("i")
tabelaLetras.add("o")
tabelaLetras.add("p")
tabelaLetras.add("a")
tabelaLetras.add("s")
tabelaLetras.add("d")
tabelaLetras.add("f")
tabelaLetras.add("g")
tabelaLetras.add("h")
tabelaLetras.add("j")
tabelaLetras.add("k")
tabelaLetras.add("l")
tabelaLetras.add("z")
tabelaLetras.add("x")
tabelaLetras.add("c")
tabelaLetras.add("v")
tabelaLetras.add("b")
tabelaLetras.add("n")
tabelaLetras.add("m")
/** PALAVRAS PT-BR */
palavras.add("Mano")
palavras.add("cara")
palavras.add("miga")
palavras.add("mana")
palavras.add("maçã")
palavras.add("banana")
palavras.add("pera")
palavras.add("uva Verde/Roxa")
palavras.add("olá")
palavrasMasculinas.add("mano")
palavrasMasculinas.add("cara")

palavrasFemininas.add("miga")
palavrasFemininas.add("mana")

comidas.add("maçã")
comidas.add("banana")
comidas.add("pera")
comidas.add("uva Verde/Roxa")

saudações.add("olá")
saudações.add("e ai mano")
saudações.add("e ai mana")
saudações.add("e ai")
saudações.add("e ai tudo bem")
saudações.add("oi")
saudações.add("oi tudo bem?")
verbos.add("comer")
verbos.add("beber")
verbos.add("andar")
verbos.add("correr")
verbos.add("falar")
verbos.add("dormir")
verbos.add("pensar")
verbos.add("fazer")
verbos.add("ir")
verbos.add("vir")
verbos.add("ver")
verbos.add("pegar")
verbos.add("abrir")
verbos.add("fechar")
verbos.add("sentar")
verbos.add("levantar")
verbos.add("desabafa mano")
bebidas.add("água")
bebidas.add("refrigerante")
bebidas.add("suco")
bebidas.add("chá")
bebidas.add("café")
bebidas.add("vitamina")
bebidas.add("leite")
bebidas.add("cerveja")
bebidas.add("pinga")
bebidas.add("vinho")
bebidas.add("vodka")
bebidas.add("catuaba")
gírias.add("mano")
gírias.add("véi")
gírias.add("truta")
gírias.add("fi")
gírias.add("pivete")
gírias.add("mina")
gírias.add("botar marcha")
gírias.add("dar fuga")
gírias.add("suave")
gírias.add("de boa")
gírias.add("top")
gírias.add("brabo")
gírias.add("é os guri")
gírias.add("oxe")
gírias.add("vixi")
gírias.add("papo reto")
gírias.add("cria")
gírias.add("do nada")
gírias.add("bolado")
gírias.add("zovo")
gírias.add("ovo")
gírias.add("minino")
gírias.add("menino")
gírias.add("garoto")
gírias.add("garota")
gírias.add("homem")
gírias.add("mulher")
