/** Copyright (C) Enzo 2025-2026 */
/** Copyright (C) Enzo inc. 2025-2026 */
/** Copyright (C) Enzo LLC 2025-2026 */
val tabelaLetras = mutableListOf<String>()
val letras = mutableListOf<String>()
val palavras = mutableListOf<String>()
val palavrasMasculinas = mutableListOf<String>()
val palavrasFemininas = mutableListOf<String>()
val comidas = mutableListOf<String>()
val saudações = mutableListOf<String>()
val verbos = mutableListOf<String>()
val bebidas = mutableListOf<String>()
val gírias = mutableListOf<String>()
data class Palavra(val texto: String, val categoria: String)
val banco = mutableListOf<Palavra>()
val nomesMasculinos = banco.filter { it.categoria == "nome_masculino" }
val nomesMasculinos = listOf("Enzo", "Gabriel", "João")
val nomesFemininos  = listOf("Maria", "Ana", "Sofia")
val nomesNeutros    = listOf("Alex", "Sam")
val gíriasSus       = listOf("sus", "suspeito", "impostor", "ventou")
nomesMasculinos.forEach { banco.add(Palavra(it, "nome_masculino")) }
nomesFemininos.forEach { banco.add(Palavra(it, "nome_feminino")) }
nomesNeutros.forEach { banco.add(Palavra(it, "nome_neutro")) }
gíriasSus.forEach { banco.add(Palavra(it, "sus")) }
val criancas_5_7 = mutableListOf<String>()
val criancas_8_12 = mutableListOf<String>()
val adolescentes = mutableListOf<String>()
val palavrasProibidas = mutableListOf<String>()
val emocaoFeliz = mutableListOf<String>()
/** LETRAS */
tabelaLetras.add("q")
tabelaLetras.add("w")
tabelaLetras.add("e")
tabelaLetras.add("r")
tabelaLetras.add("t")
tabelaLetras.add("y")
tabelaLetras.add("u")
tabelaLetras.add("i")
tabelaLetras.add("o")
tabelaLetras.add("p")
tabelaLetras.add("a")
tabelaLetras.add("s")
tabelaLetras.add("d")
tabelaLetras.add("f")
tabelaLetras.add("g")
tabelaLetras.add("h")
tabelaLetras.add("j")
tabelaLetras.add("k")
tabelaLetras.add("l")
tabelaLetras.add("z")
tabelaLetras.add("x")
tabelaLetras.add("c")
tabelaLetras.add("v")
tabelaLetras.add("b")
tabelaLetras.add("n")
tabelaLetras.add("m")
/** PALAVRAS PT-BR */
palavras.add("Mano")
palavras.add("cara")
palavras.add("miga")
palavras.add("mana")
palavras.add("maçã")
palavras.add("banana")
palavras.add("pera")
palavras.add("uva Verde/Roxa")
palavras.add("olá")
palavrasMasculinas.add("mano")
palavrasMasculinas.add("cara")

palavrasFemininas.add("miga")
palavrasFemininas.add("mana")

comidas.add("maçã")
comidas.add("banana")
comidas.add("pera")
comidas.add("uva Verde/Roxa")

saudações.add("olá")
saudações.add("e ai mano")
saudações.add("e ai mana")
saudações.add("e ai")
saudações.add("e ai tudo bem")
saudações.add("oi")
saudações.add("oi tudo bem?")
verbos.add("comer")
verbos.add("beber")
verbos.add("andar")
verbos.add("correr")
verbos.add("falar")
verbos.add("dormir")
verbos.add("pensar")
verbos.add("fazer")
verbos.add("ir")
verbos.add("vir")
verbos.add("ver")
verbos.add("pegar")
verbos.add("abrir")
verbos.add("fechar")
verbos.add("sentar")
verbos.add("levantar")
verbos.add("desabafa mano")
bebidas.add("água")
bebidas.add("refrigerante")
bebidas.add("suco")
bebidas.add("chá")
bebidas.add("café")
bebidas.add("vitamina")
bebidas.add("leite")
bebidas.add("cerveja")
bebidas.add("pinga")
bebidas.add("vinho")
bebidas.add("vodka")
bebidas.add("catuaba")
gírias.add("mano")
gírias.add("véi")
gírias.add("truta")
gírias.add("fi")
gírias.add("pivete")
gírias.add("mina")
gírias.add("botar marcha")
gírias.add("dar fuga")
gírias.add("suave")
gírias.add("de boa")
gírias.add("top")
gírias.add("brabo")
gírias.add("é os guri")
gírias.add("oxe")
gírias.add("vixi")
gírias.add("papo reto")
gírias.add("cria")
gírias.add("do nada")
gírias.add("bolado")
gírias.add("zovo")
gírias.add("ovo")
gírias.add("minino")
gírias.add("menino")
gírias.add("garoto")
gírias.add("garota")
gírias.add("homem")
gírias.add("mulher")
banco.add(Palavra("Enzo", "nome_masculino"))
banco.add(Palavra("Gabriel", "nome_masculino"))
banco.add(Palavra("João", "nome_masculino"))
banco.add(Palavra("Pedro", "nome_masculino"))
banco.add(Palavra("Maria", "nome_feminino"))
banco.add(Palavra("Ana", "nome_feminino"))
banco.add(Palavra("Beatriz", "nome_feminino"))
banco.add(Palavra("Sofia", "nome_feminino"))
banco.add(Palavra("miga", "apelido_feminino"))
banco.add(Palavra("mano", "apelido_masculino"))
banco.add(Palavra("tropa", "apelido_coletivo"))
banco.add(Palavra("cria", "apelido"))
banco.add(Palavra("Alex", "nome_neutro"))
banco.add(Palavra("Sam", "nome_neutro"))
banco.add(Palavra("sus", "giria_sus"))
banco.add(Palavra("estranho", "sus"))
banco.add(Palavra("suspeito", "sus"))
banco.add(Palavra("duvidoso", "sus"))
banco.add(Palavra("parece errado", "sus"))
banco.add(Palavra("hm?", "sus"))
banco.add(Palavra("impostor", "sus"))
banco.add(Palavra("ventou", "sus"))   // referência Among Us
banco.add(Palavra("tá estranho", "sus"))
banco.add(Palavra("algo errado aí", "sus"))
criancas_5_7.add("bola")
criancas_5_7.add("gato")
criancas_5_7.add("cachorro")
criancas_5_7.add("boneca")
criancas_5_7.add("carrinho")
criancas_5_7.add("pipoca")
criancas_5_7.add("pirulito")
criancas_5_7.add("casinha")
criancas_5_7.add("mãe")
criancas_5_7.add("pai")
criancas_5_7.add("tia")
criancas_5_7.add("tio")
criancas_5_7.add("parque")
criancas_5_7.add("escola")
criancas_5_7.add("amigo")
criancas_5_7.add("amiga")
criancas_5_7.add("quebra-cabeça")
criancas_5_7.add("desenho")
criancas_5_7.add("colorir")
criancas_5_7.add("história")
criancas_5_7.add("merenda")
criancas_5_7.add("lanche")
criancas_5_7.add("brincar")
criancas_5_7.add("pular")
criancas_5_7.add("cantar")
criancas_5_7.add("abraço")
criancas_8_12.add("tablet")
criancas_8_12.add("videogame")
criancas_8_12.add("escola")
criancas_8_12.add("recreio")
criancas_8_12.add("caderno")
criancas_8_12.add("professor")
criancas_8_12.add("brincadeira")
criancas_8_12.add("amizade")
criancas_8_12.add("desenho animado")
criancas_8_12.add("herói")
criancas_8_12.add("superpoder")
criancas_8_12.add("futebol")
criancas_8_12.add("natação")
criancas_8_12.add("bicicleta")
criancas_8_12.add("patinete")
criancas_8_12.add("computador")
criancas_8_12.add("livro")
criancas_8_12.add("história")
criancas_8_12.add("aventura")
criancas_8_12.add("parque")
criancas_8_12.add("ciência")
criancas_8_12.add("robô")
criancas_8_12.add("dinossauro")
criancas_8_12.add("coleção")
criancas_8_12.add("cartas")
criancas_8_12.add("quadrinhos")
adolescentes.add("crush")
adolescentes.add("rolê")
adolescentes.add("amizade")
adolescentes.add("chat")
adolescentes.add("timidez")
adolescentes.add("festa")
adolescentes.add("escola")
adolescentes.add("música")
adolescentes.add("headset")
adolescentes.add("streamer")
adolescentes.add("gamer")
adolescentes.add("celular")
adolescentes.add("grupo")
adolescentes.add("namoro")
adolescentes.add("tretar")
adolescentes.add("stylish")
adolescentes.add("moda")
adolescentes.add("viral")
adolescentes.add("trend")
adolescentes.add("selfie")
adolescentes.add("postar")
adolescentes.add("insegurança")
adolescentes.add("confiança")
adolescentes.add("treino")
adolescentes.add("amizade forte")
adolescentes.add("aprendizado")
palavrasProibidas.add("insulto")
palavrasProibidas.add("xingamento")
palavrasProibidas.add("violencia")
palavrasProibidas.add("ofensa")
palavrasProibidas.add("discurso de odio")
palavrasProibidas.add("conteudo adulto")
palavrasProibidas.add("bullying")
palavrasProibidas.add("preconceito")
palavrasProibidas.add("ataque pessoal")
palavrasProibidas.add("discriminacao")
palavrasProibidas.add("palavra chula")
palavrasProibidas.add("assedio")
palavrasProibidas.add("autolesao")
palavrasProibidas.add("suicidio")
palavrasProibidas.add("conteudo perigoso")
palavrasProibidas.add("tortura")
palavrasProibidas.add("armas")
palavrasProibidas.add("drogas")
palavrasProibidas.add("odio")
palavrasProibidas.add("terrorismo")
emocaoFeliz.add("sorriso")
emocaoFeliz.add("alegria")
emocaoFeliz.add("feliz")
emocaoFeliz.add("animado")
emocaoFeliz.add("divertido")
emocaoFeliz.add("orgulhoso")
emocaoFeliz.add("contente")

val emocaoTriste = mutableListOf<String>()
emocaoTriste.add("chorar")
emocaoTriste.add("tristeza")
emocaoTriste.add("sozinho")
emocaoTriste.add("desanimado")
emocaoTriste.add("cansado")
emocaoTriste.add("saudade")
emocaoTriste.add("desconforto")

val emocaoBravo = mutableListOf<String>()
emocaoBravo.add("raiva")
emocaoBravo.add("bravo")
emocaoBravo.add("irritado")
emocaoBravo.add("frustrado")
emocaoBravo.add("impaciente")
emocaoBravo.add("explodir")

val emocaoAssustado = mutableListOf<String>()
emocaoAssustado.add("medo")
emocaoAssustado.add("susto")
emocaoAssustado.add("preocupado")
emocaoAssustado.add("nervoso")
emocaoAssustado.add("tenso")
emocaoAssustado.add("assustado")
val adolescentesOdeiam = mutableListOf<String>()

adolescentesOdeiam.add("acordar cedo")
adolescentesOdeiam.add("prova surpresa")
adolescentesOdeiam.add("bronca sem motivo")
adolescentesOdeiam.add("comparacao com outros")
adolescentesOdeiam.add("falta de privacidade")
adolescentesOdeiam.add("demora no wifi")
adolescentesOdeiam.add("internet lenta")
adolescentesOdeiam.add("quando o celular trava")
adolescentesOdeiam.add("acabar a bateria")
adolescentesOdeiam.add("gente falsa")
adolescentesOdeiam.add("fofoca")
adolescentesOdeiam.add("mentira")
adolescentesOdeiam.add("quando nao respondem mensagem")
adolescentesOdeiam.add("quando respondem seco")
adolescentesOdeiam.add("barulho enquanto estao concentrados")
adolescentesOdeiam.add("chamar na frente dos outros")
adolescentesOdeiam.add("ser obrigados a socializar")
adolescentesOdeiam.add("promessas quebradas")
adolescentesOdeiam.add("proibirem de usar celular")
adolescentesOdeiam.add("tirarem o videogame")
adolescentesOdeiam.add("fazer tarefa de casa")
adolescentesOdeiam.add("esperar demais")
adolescentesOdeiam.add("serem tratados como crianca")
adolescentesOdeiam.add("injustica")
adolescentesOdeiam.add("serem ignorados")
adolescentesOdeiam.add("explicar varias vezes a mesma coisa")
adolescentesOdeiam.add("serem forçados a comer algo que nao gostam")
adolescentesOdeiam.add("aulas longas")
adolescentesOdeiam.add("ver gente brigando")
adolescentesOdeiam.add("serem interrompidos")
adolescentesOdeiam.add("conectar em redes publicas ruins")
adolescentesOdeiam.add("fila longa")
adolescentesOdeiam.add("perguntas repetitivas")
adolescentesOdeiam.add("ENEM")
adolescentesOdeiam.add("SAEB")
